name: Matrix Demo
on: push
jobs: 
  build:
    strategy:
    matrix: 
      node-versions: [12,14,16]
      operating-systems: [ubuntu-latest,windows-latest]
    runs-on: {{matrix.operating-systems}}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJs
        uses: actions/setup-node@v4
        with: 
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build